### ISSUE TITLE
Some steps never start

### ISSUE THREAD

**Issue by brunosmm** [gsmainclusivetechlab/interop-test-platform#448]
Sometimes the test cases does not execute all steps.

## Steps to reproduce

1. Execute a test case.

## Expected outcome

All steps are executed.

## Actual outcome

Some steps does not execute. Most happens in NO SUT scneario.
https://compliance.mobilemoneyapi.io/sessions/5/test-cases/151/test-runs/174
![image](https://user-images.githubusercontent.com/1554850/107588397-594e0b80-6be2-11eb-9c33-33e0cabe652d.png)

**Comment by cjol** [comment]
This is also weird because I have never seen this before in the Mojaloop test cases! I wonder if there is an error at the backend causing a crash. Next time it happens, please let me know and I can look at the laravel error log to see if there is any further iformation there.

**Comment by KolyaSirik** [comment]
Hi Christopher @cjol,
Can you look errors at the `failed_jobs` table in DB (`exception` column)?

**Comment by cjol** [comment]
All entries in that table look like this. So maybe some kind of timeout, but still not sure what is causing that
```
|  1 | redis      | default | {"uuid":"7ed7f4ae-3afa-4405-b544-3525a65fa9db","timeout":null,"id":"jdu35ALeH3EDGBzseDcZ5tIhUcyJ5Rz9","backoff":null,"displayName":"App\\Jobs\\ExecuteTestStepJob","maxTries":1,"maxExceptions":null,"retryUntil":null,"data":{"command":"O:27:\"App\\Jobs\\ExecuteTestStepJob\":14:{s:5:\"tries\";i:1;s:10:\"\u0000*\u0000session\";O:45:\"Illuminate\\Contracts\\Database\\ModelIdentifier\":4:{s:5:\"class\";s:18:\"App\\Models\\Session\";s:2:\"id\";i:1;s:9:\"relations\";a:1:{i:0;s:10:\"components\";}s:10:\"connection\";s:5:\"mysql\";}s:11:\"\u0000*\u0000testStep\";O:45:\"Illuminate\\Contracts\\Database\\ModelIdentifier\":4:{s:5:\"class\";s:19:\"App\\Models\\TestStep\";s:2:\"id\";i:151;s:9:\"relations\";a:1:{i:0;s:6:\"source\";}s:10:\"connection\";s:5:\"mysql\";}s:10:\"\u0000*\u0000testRun\";O:45:\"Illuminate\\Contracts\\Database\\ModelIdentifier\":4:{s:5:\"class\";s:18:\"App\\Models\\TestRun\";s:2:\"id\";i:21;s:9:\"relations\";a:2:{i:0;s:11:\"testResults\";i:1;s:20:\"testResults.testStep\";}s:10:\"connection\";s:5:\"mysql\";}s:3:\"job\";N;s:10:\"connection\";N;s:5:\"queue\";N;s:15:\"chainConnection\";N;s:10:\"chainQueue\";N;s:19:\"chainCatchCallbacks\";N;s:5:\"delay\";N;s:11:\"afterCommit\";N;s:10:\"middleware\";a:0:{}s:7:\"chained\";a:0:{}}","commandName":"App\\Jobs\\ExecuteTestStepJob"},"job":"Illuminate\\Queue\\CallQueuedHandler@call","attempts":1} | Illuminate\Queue\MaxAttemptsExceededException: App\Jobs\ExecuteTestStepJob has been attempted too many times or run too long. The job may have previously timed out. in /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:713
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(482): Illuminate\Queue\Worker->maxAttemptsExceededException(Object(Illuminate\Queue\Jobs\RedisJob))
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(396): Illuminate\Queue\Worker->markJobAsFailedIfAlreadyExceedsMaxAttempts('redis', Object(Illuminate\Queue\Jobs\RedisJob), 1)
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(356): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(158): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), 'redis', Object(Illuminate\Queue\WorkerOptions))
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(116): Illuminate\Queue\Worker->daemon('redis', 'default', Object(Illuminate\Queue\WorkerOptions))
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(100): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'default')
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Queue\Console\WorkCommand->handle()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call(Array)
#12 /var/www/html/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#14 /var/www/html/vendor/symfony/console/Application.php(971): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/html/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 {main} | 2021-02-02 20:14:16 |
```
